# Generated by Django 5.2.6 on 2025-10-22 19:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroFormacion',
            fields=[
                ('id_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id_talla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'administrador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_administrados', to=settings.AUTH_USER_MODEL)),
                ('almacenista', models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'almacenista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.color')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.talla')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='core.centroformacion')),
            ],
        ),
        migrations.CreateModel(
            name='Borrador',
            fields=[
                ('id_borrador', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=255)),
                ('talla', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ficha', models.PositiveIntegerField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.centroformacion')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('detalles_adicionales', models.TextField(blank=True, null=True)),
                ('tipo_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('talla_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('color_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('centro_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('programa_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('ficha', models.PositiveIntegerField(default=0)),
                ('estado_solicitud', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada'), ('despachada', 'Despachada')], default='pendiente', max_length=255)),
                ('centro_formacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.centroformacion')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.color')),
                ('id_aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='core.producto')),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.programa')),
                ('talla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.talla')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoproducto')),
            ],
        ),
    ]
