# Generated by Django 5.2.6 on 2025-09-24 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_groups_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('talla', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'administrador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_administrados', to=settings.AUTH_USER_MODEL)),
                ('almacenista', models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'almacenista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
