# Generated by Django 5.2.6 on 2025-09-25 16:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_producto_imagen_url_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('detalles_adicionales', models.TextField(blank=True, null=True)),
                ('estado_solicitud', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('borrador', 'Borrador')], default='pendiente', max_length=20)),
                ('centro_formacion', models.CharField(max_length=255)),
                ('programa', models.CharField(max_length=255)),
                ('ficha', models.PositiveIntegerField(default=0)),
                ('id_aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='core.producto')),
            ],
        ),
    ]
