# Generated by Django 5.2.6 on 2025-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='talla',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
