# Generated by Django 5.2.6 on 2025-09-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_solicitud_color_solicitud_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='centro_formacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='ficha',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='programa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
