# Generated by Django 5.2.6 on 2025-09-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_solicitud_centro_formacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada'), ('despachada', 'Despachada'), ('borrador', 'Borrador')], default='pendiente', max_length=20),
        ),
    ]
