# Generated by Django 5.2.6 on 2025-10-08 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_solicitud_estado_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('talla', models.CharField(blank=True, max_length=5)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('centro', models.CharField(blank=True, max_length=255)),
                ('programa', models.CharField(blank=True, max_length=255)),
                ('ficha', models.PositiveIntegerField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
