# Generated by Django 5.2.6 on 2025-10-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_borrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrador',
            name='id',
        ),
        migrations.AddField(
            model_name='borrador',
            name='id_borrador',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada'), ('despachada', 'Despachada')], default='pendiente', max_length=20),
        ),
    ]
