# Generated by Django 5.2.6 on 2025-10-08 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_borrador_id_borrador_id_borrador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='id_borrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.borrador'),
        ),
    ]
