# Generated by Django 5.2.6 on 2025-10-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_solicitud_id_borrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='id_borrador',
        ),
        migrations.AlterField(
            model_name='borrador',
            name='color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='borrador',
            name='talla',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='borrador',
            name='tipo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='centro_formacion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='color',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada'), ('despachada', 'Despachada')], default='pendiente', max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='ficha',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='programa',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='talla',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
